###
POST http://localhost:3000/api/users
content-type: application/json

{
    "name": "ALberto",
    "email": "correo@gmail.com",
    "pass": "pass123",
    "age": 19,
    "employment": "A",
    "phone": "1234567890",
}